# Generated by Django 3.1.5 on 2022-03-03 06:19

import app1.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.FileField(default=django.utils.timezone.now, upload_to=app1.models.image_path_and_rename),
            preserve_default=False,
        ),
    ]
