name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macOS-10.15, windows-2019 ]
        python: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
        variant: [ "py", "py-images" ]
    name: python${{ matrix.python }} on ${{ matrix.os }} ${{ matrix.variant }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install test dependency
        run: pip install tox codecov
      - name: Run tests
        run: tox
        env:
          TOXENV: ${{ matrix.variant }}
      - name: Report coverage
        run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
